---
deployment:
  tasks:
    - /bin/mkdir -p /home/klgbxdde/public_html/timeflow/ooumirceacevskopje
    - /bin/rm -rf /home/klgbxdde/public_html/timeflow/ooumirceacevskopje/static /home/klgbxdde/public_html/timeflow/ooumirceacevskopje/index.html /home/klgbxdde/public_html/timeflow/ooumirceacevskopje/manifest.json /home/klgbxdde/public_html/timeflow/ooumirceacevskopje/.htaccess /home/klgbxdde/public_html/timeflow/ooumirceacevskopje/sw.js
    - /bin/cp -rf $CURRENT_SOURCE_DIR/build/. /home/klgbxdde/public_html/timeflow/ooumirceacevskopje
