const staticClasses = [
  {
    "id": 14,
    "grade": 6,
    "section": "А"
  },
  {
    "id": 15,
    "grade": 6,
    "section": "Б"
  },
  {
    "id": 16,
    "grade": 6,
    "section": "В"
  },
  {
    "id": 18,
    "grade": 7,
    "section": "А"
  },
  {
    "id": 19,
    "grade": 7,
    "section": "Б"
  },
  {
    "id": 20,
    "grade": 7,
    "section": "В"
  },
  {
    "id": 21,
    "grade": 7,
    "section": "Г"
  },
  {
    "id": 22,
    "grade": 8,
    "section": "А"
  },
  {
    "id": 24,
    "grade": 8,
    "section": "Б"
  },
  {
    "id": 23,
    "grade": 8,
    "section": "В"
  },
  {
    "id": 25,
    "grade": 9,
    "section": "А"
  },
  {
    "id": 26,
    "grade": 9,
    "section": "Б"
  },
  {
    "id": 27,
    "grade": 9,
    "section": "В"
  }
];

const staticSchedule = [
  {
    "id": 1,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 1,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 2,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 3,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 1,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 4,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 1,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 5,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 6,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 7,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 8,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 9,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 10,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 11,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 12,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 13,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 14,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 4,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 15,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 4,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 16,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 4,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 17,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 18,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 19,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 20,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 21,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 22,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 23,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 24,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Андријана А. Николоски",
    "classroom": "21",
    "day_of_week": 5,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 25,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 1,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 26,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 27,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 1,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 28,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 29,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 30,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 31,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 32,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 33,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 34,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 35,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 36,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 37,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 38,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 4,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 39,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 4,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 40,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 4,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 41,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 42,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 43,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 44,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 45,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Македонски јазик",
    "teacher": "Јасна Матевска",
    "classroom": "14",
    "day_of_week": 5,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 46,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 47,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 1,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 48,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 1,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 49,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 1,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 50,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 51,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 52,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 53,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 54,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 55,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 2,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 56,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 57,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 58,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 59,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 60,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 4,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 61,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 4,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 62,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 63,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 64,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 65,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Англиски јазик / Мултикултурни работилници",
    "teacher": "Драгица И. Стојаноска",
    "classroom": "15",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 66,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 1,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 67,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 68,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 1,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 69,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 70,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 1,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 71,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 72,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 73,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 74,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 75,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 76,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 77,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 78,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 79,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 80,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 3,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 81,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 82,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 4,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 83,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 4,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 84,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 85,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 86,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 87,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Англиски јазик",
    "teacher": "Јулијана Гугоска",
    "classroom": "28",
    "day_of_week": 5,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 88,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 1,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 89,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 90,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 91,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 1,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 92,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 1,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 93,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 94,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 95,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 96,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 97,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 98,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 99,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 3,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 100,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 101,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 4,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 102,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 103,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 104,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Математика",
    "teacher": "Јагода Арсовска",
    "classroom": "23",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 105,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 1,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 106,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 107,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 1,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 108,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 109,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 110,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 111,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 112,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 113,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 114,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 115,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 116,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 117,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 118,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 3,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 119,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 120,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 4,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 121,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 4,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 122,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 123,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 124,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 125,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 126,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физика / Математика",
    "teacher": "Валентина Поповска",
    "classroom": "22",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 127,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 1,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 128,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 1,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 129,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 1,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 130,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 131,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 132,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 133,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 2,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 134,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 135,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 136,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 137,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 138,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 4,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 139,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 140,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 141,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 142,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Хемија",
    "teacher": "Снежана Михајловска",
    "classroom": "17",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 143,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 1,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 144,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 145,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 1,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 146,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 147,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 1,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 148,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 1,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 149,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 150,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 151,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 152,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 153,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 154,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 155,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 156,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 157,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 158,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 159,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 4,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 160,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 4,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 161,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 162,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 163,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Историја и општество / Историја",
    "teacher": "Ирена Младеновска",
    "classroom": "4",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 164,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 1,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 165,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 166,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 1,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 167,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 168,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 1,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 169,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 1,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 170,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 171,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 172,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 173,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 174,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 175,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 176,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 177,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 178,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 179,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 3,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 180,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 181,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 4,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 182,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 4,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 183,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 184,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 185,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 186,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Историја  / Географија / Истражување на родниот крај",
    "teacher": "Сузана Ангелевска",
    "classroom": "3",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 187,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 1,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 188,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 189,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 190,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 1,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 191,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 1,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 192,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 193,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 194,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 195,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 2,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 196,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 197,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 198,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 199,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 200,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 3,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 201,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Географија / Природни науки / Истражување на родниот крај",
    "teacher": "Сунчица М. Стојановиќ",
    "classroom": "16",
    "day_of_week": 3,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 202,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 1,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 203,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 204,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 205,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 206,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 207,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 208,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 4,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 209,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 210,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 211,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 4,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 212,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 213,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 214,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 215,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Техничко образование и информатика",
    "teacher": "Дејан Гацевски",
    "classroom": "27",
    "day_of_week": 5,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 216,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 3,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 217,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 218,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 3,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 219,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 220,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 4,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 221,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 4,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 222,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 223,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 224,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 225,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 226,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 227,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 228,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Ликовно образование",
    "teacher": "Влатко Костовски",
    "classroom": "2",
    "day_of_week": 5,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 229,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 1,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 230,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 231,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 232,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 233,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 234,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 2,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 235,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 2,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 236,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 237,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 3,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 238,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 3,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 239,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 240,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 241,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 4,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 242,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 243,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 244,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 245,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 246,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Музичко образование / Проекти од музичката  уметност /\r\nМузиката во нашите животи",
    "teacher": "Ангела Димитријевиќ",
    "classroom": "1",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 247,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 1,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 248,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 1,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 249,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 1,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 250,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 251,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 252,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 2,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 253,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 254,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 255,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 256,
    "class_id": 14,
    "grade": 6,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 257,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 258,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 259,
    "class_id": 16,
    "grade": 6,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 260,
    "class_id": 15,
    "grade": 6,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 261,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 262,
    "class_id": 20,
    "grade": 7,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 5,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 263,
    "class_id": 19,
    "grade": 7,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 264,
    "class_id": 21,
    "grade": 7,
    "section": "Г",
    "subject": "Физичко и здравствено образование",
    "teacher": "Андe Топузовски",
    "classroom": "",
    "day_of_week": 5,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 265,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 1,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 266,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 1,
    "start_time": "09:45",
    "end_time": "10:25"
  },
  {
    "id": 267,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 1,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 268,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 2,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 269,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 2,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 270,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 2,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 271,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 272,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 273,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 274,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 275,
    "class_id": 18,
    "grade": 7,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 276,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 3,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 277,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 278,
    "class_id": 25,
    "grade": 9,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 279,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "12:05",
    "end_time": "12:45"
  },
  {
    "id": 280,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 4,
    "start_time": "12:50",
    "end_time": "13:30"
  },
  {
    "id": 281,
    "class_id": 23,
    "grade": 8,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 5,
    "start_time": "08:00",
    "end_time": "08:40"
  },
  {
    "id": 282,
    "class_id": 22,
    "grade": 8,
    "section": "А",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 5,
    "start_time": "08:45",
    "end_time": "09:25"
  },
  {
    "id": 283,
    "class_id": 24,
    "grade": 8,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 5,
    "start_time": "10:30",
    "end_time": "11:10"
  },
  {
    "id": 284,
    "class_id": 26,
    "grade": 9,
    "section": "Б",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 5,
    "start_time": "11:20",
    "end_time": "12:00"
  },
  {
    "id": 285,
    "class_id": 27,
    "grade": 9,
    "section": "В",
    "subject": "Физичко и здравствено образование",
    "teacher": "Илија Јанковски",
    "classroom": "",
    "day_of_week": 5,
    "start_time": "12:05",
    "end_time": "12:45"
  }
];

export { staticClasses, staticSchedule };
